### ISSUE TITLE
에러 표준 인터페이스 구성 제안

### ISSUE THREAD

**Issue by suakang17** [team-waff1e/Backend#15]
- Auth api를 작성하는 중 에러 표준이 정해져 있지 않아서 우선 임의로 상태코드만 변경하는 방식으로 구현했습니다.
- 협업인 만큼 에러 표준이 존재해야 백엔드끼리도, 프론트에서 응답을 받아 볼 때도 수월할 거 같습니다.
- 에러 인터페이스 정의의 필요성
  - 에러메시지로 나가는 포맷의 일관성
    e.g 모듈 a에서 발생한 예외에 응답하는 메세지는 에러코드랑 설명을 리턴해준다고 하고, 모듈 b에서 발생한 예외의 경우는 코드만을 리턴해 준다면 리턴 타입이 달라 통합해서 처리할 수 없습니다.

**Comment by JehunYoo** [comment]
`io.github.teamwaff1e.waffle.global.exception.ErrorCode` 만들었습니다! 여기에 에러 상세코드 정의해서 사용하면 될 것 같습니다.
